### ISSUE TITLE
consider making this a template repo

### ISSUE THREAD

**Issue by broeder-j** [materialscloud-org/structure-property-visualizer#3]
Hi, @ltalirz 

If I understood correctly you want this repository (or some other repository) to serve as a template for discover sections on materialscloud or similar apps.
A template is different from a fork. The same user or organisation cannot have several forks of one project. Consider making this repo a template:
https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template
Forks are basicly for contributions to the original repo, and templates to start a 'new project' from the template. In the new repository one will see that it used another repo as a template. 
Unfortunatly, one cannot see in the original repo all the projects which use it as a template, like with forks...

**Comment by ltalirz** [comment]
Hi Jens, thanks for pointing this out - you're absolutely right, of course, and I wasn't aware of this "template" switch.
@kjappelbaum rightfully mentioned that one should probably make this repo a cookiecutter recipe, but until then the "template" repository seems like a good alternative.

**Comment by broeder-j** [comment]
Thank you!
